name: Training Pipeline
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
jobs:
  train:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run training pipeline
        run: python pipelines/training_pipeline.py
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
          TRAINING_WINDOW_DAYS: "90"
          USE_EDA_BEST_WINDOW: "false"
          DAGSHUB_MLFLOW_URI: ${{ secrets.DAGSHUB_MLFLOW_URI }}
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          DAGSHUB_EXPERIMENT: ${{ secrets.DAGSHUB_EXPERIMENT }}
          DAGSHUB_MODEL_STAGE: ${{ secrets.DAGSHUB_MODEL_STAGE }}
